// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_BETLRa6Nw3JKNr6no2THINpsFFiUv8',
    appId: '1:74873326542:web:6408e817f464a0742ab99f',
    messagingSenderId: '74873326542',
    projectId: 'coffee-app-f8fcf',
    authDomain: 'coffee-app-f8fcf.firebaseapp.com',
    storageBucket: 'coffee-app-f8fcf.firebasestorage.app',
    measurementId: 'G-LKHKDYW5DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2IZNScAxgacd0ahPbdKR99jZVRtM_r_I',
    appId: '1:74873326542:android:169357e6298196542ab99f',
    messagingSenderId: '74873326542',
    projectId: 'coffee-app-f8fcf',
    storageBucket: 'coffee-app-f8fcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7pzOZS8WuQUDO53C-Qgf9Kt9acYMlDMY',
    appId: '1:74873326542:ios:523d85842358ef362ab99f',
    messagingSenderId: '74873326542',
    projectId: 'coffee-app-f8fcf',
    storageBucket: 'coffee-app-f8fcf.firebasestorage.app',
    iosBundleId: 'com.example.coffeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7pzOZS8WuQUDO53C-Qgf9Kt9acYMlDMY',
    appId: '1:74873326542:ios:523d85842358ef362ab99f',
    messagingSenderId: '74873326542',
    projectId: 'coffee-app-f8fcf',
    storageBucket: 'coffee-app-f8fcf.firebasestorage.app',
    iosBundleId: 'com.example.coffeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg_BETLRa6Nw3JKNr6no2THINpsFFiUv8',
    appId: '1:74873326542:web:5f698033171e87fd2ab99f',
    messagingSenderId: '74873326542',
    projectId: 'coffee-app-f8fcf',
    authDomain: 'coffee-app-f8fcf.firebaseapp.com',
    storageBucket: 'coffee-app-f8fcf.firebasestorage.app',
    measurementId: 'G-N5LEQ5BKXB',
  );
}
